### ISSUE TITLE
Color characters don't work on OSX with bash

### ISSUE THREAD

**Issue by stiemannkj1** [kbenzie/git-prompt#4]
On OSX with GNU `bash` versions 4.3.33(1)-release (x86_64-apple-darwin14.0.0) and 3.2.57(1)-release, the color cannot be changed in `git-prompt`.
# Steps to reproduce:
1. Start up an interactive `bash` prompt
   
   ```
   bash -i
   ```
2. Run the following command:
   
   ```
   echo `./git-prompt untracked '\e[0;31m…'`
   ```
## Expected output:

```
(master|[red]…)[/red]
```
## Actual output:

```
(master|\e[0;31m…)
```

I also tested: `echo `./git-prompt untracked '%{\e[0;31m%}…'``; which output: `(master|%{\e[0;31m%}…)`.

**Comment by kbenzie** [comment]
I've not tested using bash yet, this issue is related to the escape characters used by zsh to specify a block of characters should not be added to the length of the prompt.

In zsh these controls characters are `%{` and `%}` where as in bash they are `\[` and `\]`.

Also note that in my experience `echo` does not output colors to the terminal, when I do color code testing I use `printf` as a drop in replacement for this instead.

This is on my todo list, however there are a couple of bugs in the tool itself I want to fix first.

**Comment by stiemannkj1** [comment]
Oops, sorry to waste your time, once I tried it with `printf` it worked. Closing.
